### ISSUE TITLE
Error: 'rlimit_as' is not an exported object from 'namespace:RAppArmor'

### ISSUE THREAD

**Issue by XeZZoR** [jeroen/RAppArmor#24]
I just upgraded from R 3.2 to 3.5 and reinstalled the package. Now I get the following Error:
Error: 'rlimit_as' is not an exported object from 'namespace:RAppArmor'

The examples still show this function but it seems to be removed.

**Comment by jeroen** [comment]
This function has moved to the unix package. Try `unix::rlimit_as()`

**Comment by XeZZoR** [comment]
That seems to work! Thank you very much. Please update the prefix in the examples (They are not touched 6 years)

**Comment by jeroen** [comment]
Which examples exactly do you mean?

**Comment by XeZZoR** [comment]
https://github.com/jeroen/RAppArmor/blob/master/examples/limits.R

Those do not work without the unix:: prefix as supplied there.

**Comment by jeroen** [comment]
Ah those files are some old remnants. The actual examples are in the manual page.

**Comment by XeZZoR** [comment]
Yes they are not maintained for quite some time. Just remove em with a link or something to the actual man page. Thank you for your fast response and help :)

**Comment by jeroen** [comment]
I've changed unix into a 'Depends' such that the old examples work again.
